// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package curiosity

import (
	"github.com/danielmesquitta/openai-web-scraper/internal/config"
	"github.com/danielmesquitta/openai-web-scraper/internal/pkg/validator"
	"github.com/danielmesquitta/openai-web-scraper/internal/provider/scraper/pw"
)

// Injectors from wire.go:

func NewGenerateCuriosities() *GenerateCuriosities {
	validate := validator.NewValidate()
	env := config.LoadEnv(validate)
	playWrightScraper := pw.NewPlayWrightScraper(env)
	generateCuriosities := newGenerateCuriosities(env, playWrightScraper)
	return generateCuriosities
}
