package config

var breeds = []string{
	"beagle",
	"chihuahua",
	"english-springer-spaniel",
	"pit-bull",
	"saint-bernard",
	"border-collie",
	"corgi",
	"french-bulldog",
	"pomeranian",
	"shih-tzu",
	"boxer",
	"dachshund",
	"german-shepherd",
	"poodle",
	"siberian-husky",
	"bulldog",
	"dalmatian",
	"golden-retriever",
	"pug",
	"staffordshire-terrier",
	"cavalier-king-charles-spaniel",
	"english-cocker-spaniel",
	"great-dane",
	"rottweiler",
	"yorkshire-terrier",
}
